import { ColumnDef } from "./types"

export const VEHICLE_FIELDS: ColumnDef[] = [
  {
    id: 'vin',
    label: 'VIN',
    type: 'text',
    required: true,
    editable: true,
  },
  {
    id: 'year',
    label: 'Year',
    type: 'number',
    required: true,
    editable: true,
  },
  {
    id: 'make',
    label: 'Make',
    type: 'text',
    required: true,
    editable: true,
  },
  {
    id: 'model',
    label: 'Model',
    type: 'text',
    required: true,
    editable: true,
  },
  {
    id: 'trim',
    label: 'Trim',
    type: 'dropdown',
    options: [
      'Base',
      'LX',
      'EX',
      'EX-L',
      'Touring',
      'Sport',
      'Limited',
      'Premium',
      'Other',
    ],
    editable: true,
  },
  {
    id: 'primaryUse',
    label: 'Primary Use',
    type: 'dropdown',
    options: [
      'Commute',
      'Business',
      'Pleasure',
      'Farm',
      'Other',
    ],
    required: true,
    editable: true,
  },
  {
    id: 'annualMileage',
    label: 'Annual Mileage',
    type: 'number-with-unit',
    unit: 'mi',
    required: true,
    editable: true,
  },
  {
    id: 'ownershipType',
    label: 'Owned, Leased or Financed',
    type: 'radio',
    radioOptions: [
      { value: 'Own', label: 'Own' },
      { value: 'Lease', label: 'Lease' },
      { value: 'Finance', label: 'Finance' },
    ],
    editable: true,
  },
  {
    id: 'ownershipLength',
    label: 'Ownership Length',
    type: 'dropdown',
    options: [
      '< 1 year',
      '+1 year',
      '+2 years',
      '+3 years',
      '+4 years',
      '+5 years',
      '+6 years',
      '+7 years',
      '+8 years',
      '+9 years',
      '+10 years',
      '+10+ years',
    ],
    required: true,
    editable: true,
  },
  {
    id: 'garagingZipSame',
    label: 'Is the garaging ZIP the same as the primary address?',
    type: 'radio',
    radioOptions: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
    ],
    editable: true,
  },
]

